{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "platform-ws.fullname" . }}
  labels:
    {{- include "platform-ws.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | quote }}

{{- if or .Values.externalSecret.dataFromFind .Values.externalSecret.dataFromExtract }}

{{- if .Values.externalSecret.hostRemoteRef.key }}
  data:
    - secretKey: rds_host
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ tpl (.Values.externalSecret.hostRemoteRef.key | toString) $ | quote }}
        metadataPolicy: None
        {{- if .Values.externalSecret.hostRemoteRef.property }}
        property: {{ tpl (.Values.externalSecret.hostRemoteRef.property | toString) $ | quote }}
        {{- end }}
{{- end }}

  dataFrom:
{{- if .Values.externalSecret.dataFromExtract }}
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ tpl (.Values.externalSecret.dataFromExtract.key | toString) $ | quote }}
{{- else }}
    - find:
        conversionStrategy: Default
        decodingStrategy: None
{{- if .Values.externalSecret.dataFromFind.path }}
        path: {{ .Values.externalSecret.dataFromFind.path | quote }}
{{- end }}
        tags:
          {{- range $k, $v := .Values.externalSecret.dataFromFind.tags }}
          {{ $k | quote }}: {{ $v | quote }}
          {{- end }}
{{- end }}

{{- else }}

  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ tpl (.remoteRef.key | toString) $ | quote }}
        metadataPolicy: None
        {{- if .remoteRef.property }}
        property: {{ tpl (.remoteRef.property | toString) $ | quote }}
        {{- end }}
    {{- end }}

{{- end }}

  target:
    name: {{ include "platform-ws.fullname" . }}
    creationPolicy: Owner
    deletionPolicy: Retain

{{- if or .Values.externalSecret.dataFromFind .Values.externalSecret.dataFromExtract }}
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
{{- if .Values.externalSecret.hostRemoteRef.key }}
        DB_HOST: {{ printf "{{ index . \"rds_host\" }}" | quote }}
{{- end }}
        DB_DEBUG: {{ printf "{{ . | toJson }}" | quote }}

{{- if .Values.externalSecret.dataFromExtract }}

        DB_USER: {{ printf "{{ index . \"username\" }}" | quote }}
        DB_PASSWORD: {{ printf "{{ index . \"password\" }}" | quote }}

{{- else }}

        DB_USER: {{ printf "{{- $u := \"\" -}}{{- range $k, $v := . -}}{{- if and (not $u) (contains \"rds_db-\" $k) -}}{{- $m := fromJson $v -}}{{- $u = index $m \"username\" -}}{{- end -}}{{- end -}}{{ $u }}" | quote }}

        DB_PASSWORD: {{ printf "{{- $p := \"\" -}}{{- range $k, $v := . -}}{{- if and (not $p) (contains \"rds_db-\" $k) -}}{{- $m := fromJson $v -}}{{- $p = index $m \"password\" -}}{{- end -}}{{- end -}}{{ $p }}" | quote }}

{{- end }}

{{- end }}
{{- end }}