apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform-worker.fullname" . }}-meta
  labels:
    {{- include "platform-worker.labels" . | nindent 4 }}
data:
  gitops.json: |
    {"release":"{{ .Release.Name }}","chart":"{{ .Chart.Name }}","version":"{{ .Chart.Version }}"}
